install.packages("RVAideMemoire")
install.packages("car")
install.packages("MuMin")
install.packages("R2admb")
install.packages("glmmADMB", repos=c("http://glmmadmb.r-forge.r-project.org/repos", getOption("repos")), type="source")
